# Generated by Django 2.2.6 on 2019-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category_title', models.CharField(max_length=100, unique=True)),
                ('category_slug', models.CharField(max_length=100, unique=True)),
                ('category_status', models.BooleanField(default=1)),
                ('category_thumbnail', models.ImageField(upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
