# Generated by Django 2.2.6 on 2019-11-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_thumbnail',
        ),
    ]
