# Generated by Django 2.2.6 on 2019-11-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0002_remove_category_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sub_category_title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sub_category_slug', models.CharField(max_length=100, unique=True)),
                ('sub_category_status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='admin_backend.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
